thanks to : https://medium.com/@ian.dzindo01/what-is-numpy-newaxis-and-when-to-use-it-8cb61c7ed6ae

`newaxis` expression is used to increase the dimension of the existing array by one more dimension, when used once. Thus,
- 1D -> 2D
- 2D -> 3D
- 3D -> 4D
- and so on. it's role is quite simple and yet there are plenty of problems where it's a life saver.

In [3]:
# Np.newaxis comes in very handy when you want to explicitly 
# convert an 1D array to either a row vector or a column vector.
import numpy as np
arr = np.arange(4)
arr.shape

(4,)

In [5]:
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis,:]
row_vec.shape

(1, 4)

In [6]:
# make it as column vector by inserting an axis along second dimension
col_vec = arr[:,np.newaxis]
col_vec.shape

(4, 1)

Scenario 2: When we want to make use of `numpy broadcasting` as part of some `operation`, for instance while doing `addition` of some arrays. The term numpy broadcasting describes how numpy treats arrays with `different shapes` during arithmetic operation. The smaller array, subject to some constraints, is “broadcast” across the larger arrays so that they have compatible shapes.

In [7]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

In [8]:
x1 + x2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [15]:
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [18]:
x2_new = x2[:,np.newaxis]
x1,x2_new

(array([1, 2, 3, 4, 5]), array([[5],
        [4],
        [3]]))

In [17]:
x1 + x2_new

array([[ 6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8]])

Scenario 3: You can use np.newaxis more than once to promote the array to higher dimensions.

In [21]:
arr = np.arange(5*5).reshape(5,5)
arr.shape

(5, 5)

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# promoting 2D array to a 5D array
arr_5D = arr[np.newaxis, ..., np.newaxis, np.newaxis]

In [23]:
arr_5D.shape

(1, 5, 5, 1, 1)