In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib as mpl
import matplotlib.pylab as plt
import seaborn as sns
import scipy as sp

In [3]:
X = np.array([
    [0, 1, 1, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [0, 1, 1, 0]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [35]:
from sklearn.naive_bayes import BernoulliNB
model_bern = BernoulliNB().fit(X, y)

In [36]:
fc = model_bern.feature_count_
fc

array([[4., 4., 3., 4.],
       [4., 5., 6., 6.]])

without smoothing

In [37]:
fc / np.repeat(model_bern.class_count_[:, np.newaxis], 4, axis=1)

array([[1.        , 1.        , 0.75      , 1.        ],
       [0.66666667, 0.83333333, 1.        , 1.        ]])

with smoothing

In [38]:
theta = np.exp(model_bern.feature_log_prob_)
theta

array([[0.83333333, 0.83333333, 0.66666667, 0.83333333],
       [0.625     , 0.75      , 0.875     , 0.875     ]])

In [39]:
x_new = np.array([1, 1, 0, 0])

bernoulli-distribution

In [40]:
p = ((theta ** x_new) * (1 - theta) ** (1 - x_new)).prod(axis=1)\
    * np.exp(model_bern.class_log_prior_)
p / p.sum()

array([0.77835208, 0.22164792])

In [48]:
p.sum()

0.01982663001543209

In [73]:
X = np.array([    
    [3, 4, 1, 2],
    [3, 5, 1, 1],
    [3, 3, 0, 4],
    [3, 4, 1, 2],
    [1, 2, 1, 4],
    [0, 0, 5, 3],
    [1, 2, 4, 1],
    [1, 1, 4, 2],
    [0, 1, 2, 5],
    [2, 1, 2, 3]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [74]:
from sklearn.naive_bayes import MultinomialNB
model_mult = MultinomialNB().fit(X, y)

In [75]:
model_mult.classes_


array([0, 1])

In [76]:
model_mult.class_count_


array([4., 6.])

In [77]:
np.exp(model_mult.class_log_prior_)

array([0.4, 0.6])

In [78]:
fc = model_mult.feature_count_
fc

array([[12., 16.,  3.,  9.],
       [ 5.,  7., 18., 18.]])

In [79]:
fc / np.repeat(fc.sum(axis=1)[:, np.newaxis], 4, axis=1)


array([[0.3       , 0.4       , 0.075     , 0.225     ],
       [0.10416667, 0.14583333, 0.375     , 0.375     ]])

In [80]:
model_mult.alpha


1.0

In [81]:
(fc + model_mult.alpha) / \
(np.repeat(fc.sum(axis=1)[:, np.newaxis], 4, axis=1) + model_mult.alpha * X.shape[1])

array([[0.29545455, 0.38636364, 0.09090909, 0.22727273],
       [0.11538462, 0.15384615, 0.36538462, 0.36538462]])

In [82]:
(fc + model_mult.alpha) / \
(np.repeat(fc.sum(axis=1)[:, np.newaxis], 4, axis=1) + model_mult.alpha * X.shape[1])

array([[0.29545455, 0.38636364, 0.09090909, 0.22727273],
       [0.11538462, 0.15384615, 0.36538462, 0.36538462]])

In [83]:
x_new = np.array([10, 10, 10, 10])
model_mult.predict_proba([x_new])

array([[0.38848858, 0.61151142]])

In [84]:
p = (theta ** x_new).prod(axis=1)*np.exp(model_bern.class_log_prior_)
p / p.sum()

array([0.57876898, 0.42123102])

In [85]:
theta

array([[0.83333333, 0.83333333, 0.66666667, 0.83333333],
       [0.625     , 0.75      , 0.875     , 0.875     ]])

In [86]:
x_new

array([10, 10, 10, 10])

In [87]:
theta**x_new

array([[0.16150558, 0.16150558, 0.01734153, 0.16150558],
       [0.00909495, 0.05631351, 0.26307558, 0.26307558]])

In [91]:
p = (theta ** x_new).prod(axis=1)*np.exp(model_bern.class_log_prior_)
p

array([2.92220056e-05, 2.12679249e-05])

In [92]:
p.sum()

5.0489930484398445e-05

In [93]:
p/p.sum()

array([0.57876898, 0.42123102])

In [99]:
X = np.array([[1,1,0],
             [1,0,0],
             [0,0,1],
              [0,1,1],])
y = np.array([0,0,1,1])
x_new = np.array([[1,0,0]])

In [100]:
model_mult = MultinomialNB().fit(X,y)

In [101]:
fc = model_mult.feature_count_
fc

array([[2., 1., 0.],
       [0., 1., 2.]])