In [1]:
import numpy as np

In [2]:
array = np.array([0,1,2,3,4,5])
array

array([0, 1, 2, 3, 4, 5])

In [4]:
size = int(1E6)
%timeit for x in range(size):x**2
%timeit for x in np.arange(size):x**2

294 ms ± 2.82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
156 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [6]:
np.random.seed(0)
rd = np.random.rand(10)
rdn = np.random.randn(10)
rd,rdn

(array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]),
 array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]))

In [7]:
r=np.random.randint(10,size=(3,4))
r

array([[9, 9, 0, 4],
       [7, 3, 2, 7],
       [2, 0, 0, 4]])

In [9]:
np.random.shuffle(r)
r

array([[2, 0, 0, 4],
       [9, 9, 0, 4],
       [7, 3, 2, 7]])

In [16]:
r= np.random.choice(5,100)

In [17]:
index,count = np.unique(r,return_counts=True)
index,count

(array([0, 1, 2, 3, 4]), array([18, 23, 17, 26, 16], dtype=int64))

In [34]:
np.random.seed(0)
na1 = np.random.randint(10,size= (2,3))
na2 = np.random.randint(10,size= (2,3))
print(na1)
print(na2)

[[5 0 3]
 [3 7 9]]
[[3 5 2]
 [4 7 6]]


In [40]:
na3=np.stack((na1,na2))
print(na3)
na3.shape

[[[5 0 3]
  [3 7 9]]

 [[3 5 2]
  [4 7 6]]]


(2, 2, 3)

In [39]:
na3=np.stack((na1,na2),axis=1)
print(na3)
na3.shape

[[[5 0 3]
  [3 5 2]]

 [[3 7 9]
  [4 7 6]]]


(2, 2, 3)

In [48]:
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [51]:
data[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [54]:
np.random.seed(0)
r1=np.random.randint(10,size=(2,3))
r2=np.random.randint(10,size=(3,2))
r3=np.random.randint(10,size=(3,3))

In [55]:
np.concatenate([r1,r3])

array([[5, 0, 3],
       [3, 7, 9],
       [8, 8, 1],
       [6, 7, 7],
       [8, 1, 5]])

In [57]:
np.concatenate([r2,r3],axis=1)

array([[3, 5, 8, 8, 1],
       [2, 4, 6, 7, 7],
       [7, 6, 8, 1, 5]])

In [58]:
r=np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
r1=np.split(r,[5])
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [60]:
r1,r2,r3,r4,r5=np.split(r,[2,4,6,8])
r1,r2,r3,r4,r5

(array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]))

In [61]:
r = np.random.randint(10,size=(4,6))
r

array([[9, 8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7, 0],
       [1, 9, 9, 0, 4, 7]])

In [65]:
r1,r2=np.vsplit(r,[2])
print(r1)
print(r2)

[[9 8 9 4 3 0]
 [3 5 0 2 3 8]]
[[1 3 3 3 7 0]
 [1 9 9 0 4 7]]


In [67]:
r1,r2=np.hsplit(r,[3])
print(r1)
print(r2)

[[9 8 9]
 [3 5 0]
 [1 3 3]
 [1 9 9]]
[[4 3 0]
 [2 3 8]
 [3 7 0]
 [0 4 7]]


In [68]:
r1=np.random.randint(10,size=(3,3))
r1

array([[3, 2, 7],
       [2, 0, 0],
       [4, 5, 5]])

In [72]:
np.sort(np.sort(r1),axis=0)

array([[0, 0, 2],
       [2, 3, 5],
       [4, 5, 7]])

In [71]:
np.sort(r1,axis=0)

array([[2, 0, 0],
       [3, 2, 5],
       [4, 5, 7]])

In [74]:
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("min : {}".format(r_num.min()))
print("max : {}".format(r_num.max()))
print("argmin : {}".format(r_num.argmin())) # 최소값 위치
print("argmax : {}".format(r_num.argmax())) # 최대값 위치
print("mean : {}".format(r_num.mean()))

random matrix : 
[[6 0 6]
 [6 2 1]]
min : 0
max : 6
argmin : 1
argmax : 0
mean : 3.5
