based on : https://datascienceschool.net/view-notebook/6c6d450cb2ee49558856fd924b326e00/

Im gonna deal with keyword about support vector machine mainly

- 퍼셉트론은 가장 단순하고 빠른 판별 함수 기반 분류 모형이지만 판별 경계선이 유니크하게 존재하지 않는다는 특징이 있다.(수렴하지 않는다. Stochastic grandient descent)
- 서포트 벡터 머신은 퍼셉트론 기반의 모형에 가장 안정적인 판별 경계선을 찾기 위한 `제한 조건`을 추가한 모형이다.

- 판별 함수 모형은 라벨링을 1, -1 로 이진 분류 한다. 1,0이 아니다.
- 데이터(라벨 데이터)가 양의 값이면 판별 함수는 0이상이다.
- 데이터(라벨 데이터)가 음의 값이면 판별 함수는 0이하이다.
- 서포트 벡터는 수많은 데이터(라벨을 가지게 될)들 중에서 판별 함수와 가장 근접해 있고, 데이터 중에서 판별 함수의 경계에 가장 최전방에 가있는 데이터 요소를 일컫는다.
- 서포트 벡터 머신은 판별 함수를 설정하는 데에 있어서 이러한 서포트 벡터 요소들에 집중해서 유니크한 판별 함수식을 설정한다.
- 양의 서포트를 판별 함수의 값이 1이 되게끔 설정하고, 음의 서포트를 판별 함수의 값이 -1이 되게끔 설정한다.
- 그런 후에 양쪽에 가중치 벡터의 프로베니우스 거리를 나누어주면 프로젝션 거리 식이 된다. 
- 양의 프로젝션과 음의 프로젝션을 합해주면 이를 마진이라고 한다.
- 마진값이 클수록 서포트 벡터가 판결 함수식에 멀리 있는 것이고 멀리 있을 수록 더 좋은 판결 함수가 된다.
- 또한 모든 표본 데이터에 대해 분류는 제대로 되어야 하므로 부등식 제한 조건을 추가한다.
- 부등식 제한 조건은 실제 라벨값과 판결함수 식을 곱한 것이 1보다 크거나 같다는 식이다.
- 1보다 크거나 같다는 이야기는 분류가 제대로 되었다는 뜻이다.
- 라그랑주 승수법을 사용해서 최소화 목적 함수를 계산한다.
- 최적화 문제를 풀어서 구해야 할 모수는 가중치, 직선의 방정식의 상수, 그리고 라그랑주 승수 '람다'이다.
- 여기서 중요한 조건이 튀어나오는데 바로, 라그랑주 승수 '람다'에 관한 것이다.
- 카루시-쿤터커 조건에 따르면 부등식 제한 조건을 통해 발생한 라그랑주 승수의 람다, 또는 그 안에 있는 등식(부등식을 등식으로 만든 것) 둘 중에 하나가 0이 되어야 한다. 즉, '서포트 벡터' 인 경우에는 람다가 0이 된다.
- '듀얼 폼'은 원래 구해야 할 모수 3개를 1개로 줄여주기 위해 위해서 계산한 최적화 문제를 이차 형식으로 바꿔서 간단하게 컴퓨팅할 수 있게 만든 것이다.

In [18]:
from sklearn.datasets import load_iris
iris = load_iris()
X,y = iris.data, iris.target

In [24]:
X = X[:100,:2]
y = y[:100]
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.1],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [25]:
from sklearn.svm import SVC

In [32]:
model = SVC(kernel='linear',C=1e10).fit(X,y)

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,model.predict(X))

array([[50,  0],
       [ 0, 50]])

In [34]:
model.n_support_

array([2, 2], dtype=int32)

In [35]:
model.support_

array([36, 41, 57, 84], dtype=int32)

In [36]:
model.support_vectors_

array([[5.5, 3.5],
       [4.5, 2.3],
       [4.9, 2.4],
       [5.4, 3. ]])

In [37]:
model.classes_

array([0, 1])

- 만약 데이터가 직선인 판별 경계선으로 나누어지지 않는 즉, 선형 분리가 불가능한 경우에는 다음과 같이 슬랙 변수를 사용하여 개별적인 오차를 허용할 수 잇다.
- 양의 라벨 데이터를 가지게 되는 값들을 판별 함수에서는 1 이상의 값을 가졌고,
- 음의 라벨 데이터를 가지게 되는 값들을 판별 함수에서는 -1 이하의 값을 가지게 했다.
- -0보다 크거나 같은 슬랙 변수들을 각각 1,-1에 더하게 되면 나이브한 범위 즉, 좀 더 유연한 범위의 판별 함수식을 가지게 해준다. 즉 마진이 작아지게 된다. 
- 추가된 부등식을 고려해서 라그랑지 승수를 적용한 최적화를 계산해준다.

- based on : http://scikit-learn.org/stable/modules/svm.html#svm-classification

#### 연습 문제 1
- 붓꽃 문제를 서포트 벡터 머신으로 풀어보자. 다음과 같은 데이터만 사용한 이진 분류 문제로 바꾸어 풀어본다. 위의 예제와 마찬가지로 커널 인수 kernel과 슬랙 변수 가중치 인수 C는 각각 linear, 1e10으로 한다.

    - 특징 변수를 꽃받침의 길이와 폭만 사용한다.
    - 붓꽃 종을 Setosa와 Versicolour만 대상으로 한다.

In [50]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
dfX = pd.DataFrame(iris.data,columns=iris.feature_names)
dfy = pd.DataFrame(iris.target,columns=['y'])

In [42]:
dfX = dfX.iloc[:100,0:2]
dfy = dfy.iloc[:100]

In [44]:
from sklearn.svm import SVC
model1 = SVC(kernel='linear',C=1e10).fit(X,y)

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(dfy.values,model1.predict(dfX))

array([[50,  0],
       [ 0, 50]])

#### 연습 문제

- 붓꽃 문제를 서포트 벡터 머신으로 풀어보자. 다음과 같은 데이터만 사용한 이진 분류 문제로 바꾸어 풀어본다. 위의 예제와 마찬가지로 커널 인수 kernel는 각각 linear로 한다. 슬랙 변수 가중치 인수 C를 여러가지 값으로 바꾸어 보면서 서포트가 어떻게 바뀌는지 살펴본다.

    - 특징 변수를 꽃잎의 길이와 폭만 사용한다.
    - 붓꽃 종을 Virginica와 Versicolour만 대상으로 한다.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
dfX = pd.DataFrame(iris.data,columns=iris.feature_names)
dfy = pd.DataFrame(iris.target,columns=['y'])

In [51]:
dfX = dfX.iloc[51:,2:]
dfy = dfy.iloc[51:]

In [82]:
from sklearn.svm import SVC
def chgslackvar(c):
    model = SVC(kernel='linear',C=c)
    return model

In [84]:
from sklearn.model_selection import KFold,cross_val_score
score_ls =[]
kfold = KFold(5)
for c in np.arange(1,100,10):
    model = chgslackvar(c).fit(dfX,dfy)
    score_ls.append(cross_val_score(model,dfX,dfy,cv=kfold))

/home/hskimim/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/hskimim/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/hskimim/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/hskimim/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please chan

In [86]:
np.mean(score_ls,axis=1)

array([0.92947368, 0.91894737, 0.90894737, 0.90894737, 0.90894737,
       0.90894737, 0.90894737, 0.90894737, 0.90894737, 0.90894737])

- based on : https://datascienceschool.net/view-notebook/69278a5de79449019ad1f51a614ef87c/